set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(TARGET_TRIPLET "arm-none-eabi-")

# default to Debug build
if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE "Debug" CACHE STRING
        "Choose the type of build, options are: Debug Release." FORCE)
endif()

find_program(COMPILER_ON_PATH "${TARGET_TRIPLET}gcc${TOOLCHAIN_EXT}")

# Perform compiler test with the static library
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_C_COMPILER    ${TARGET_TRIPLET}gcc${ARM_COMPILER_EXT})
set(CMAKE_CXX_COMPILER  ${TARGET_TRIPLET}g++${ARM_COMPILER_EXT})
set(CMAKE_ASM_COMPILER  ${TARGET_TRIPLET}gcc${ARM_COMPILER_EXT})
set(CMAKE_LINKER        ${TARGET_TRIPLET}gcc${ARM_COMPILER_EXT})
set(CMAKE_SIZE_UTIL     ${TARGET_TRIPLET}size${ARM_COMPILER_EXT})
set(CMAKE_OBJCOPY       ${TARGET_TRIPLET}objcopy${ARM_COMPILER_EXT})
set(CMAKE_OBJDUMP       ${TARGET_TRIPLET}objdump${ARM_COMPILER_EXT})
set(CMAKE_NM_UTIL       ${TARGET_TRIPLET}gcc-nm${ARM_COMPILER_EXT})
set(CMAKE_AR            ${TARGET_TRIPLET}gcc-ar${ARM_COMPILER_EXT})
set(CMAKE_RANLIB        ${TARGET_TRIPLET}gcc-ranlib${ARM_COMPILER_EXT})

set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
