on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.2.2
        target: esp32
        path: 'firmware'
        command: idf.py build -DBUILD_STRICT=1
